/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FSGui;

import static com.sun.corba.se.impl.util.Utility.printStackTrace;
import java.util.Date;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.util.TooManyListenersException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;
import static javax.swing.text.DefaultCaret.ALWAYS_UPDATE;

/**
 *
 * @author Jonah Lou
 */
public class FireScoutGui extends javax.swing.JFrame {

    private String MY_PORT = "COM17";

    private TwoWaySerialComm mySerialComm;

    /**
     * Creates new form FireScoutGui
     */
    public FireScoutGui() {

        initComponents();

        DefaultCaret caret = (DefaultCaret) jTextAreaLog.getCaret();
        caret.setUpdatePolicy(ALWAYS_UPDATE);

        String s = (String) JOptionPane.showInputDialog(null, "Enter COM port:\n", "Welcome to FireScout Control Center", JOptionPane.PLAIN_MESSAGE, null, null, "COM17");

        if ((s == null) && (s.length() <= 0)) {
            System.exit(0);
        }

        MY_PORT = s;
        mySerialComm = new TwoWaySerialComm(MY_PORT);
        mySerialComm.initialize();

        jTextFieldComPort.setText("Connected to " + s + ".");

        try {
            mySerialComm.serialPort.addEventListener(new GUISerialPortEventListener());
        } catch (TooManyListenersException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBase = new javax.swing.JPanel();
        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanelQuadStatus = new javax.swing.JPanel();
        jPanelCmdCtrBase = new javax.swing.JPanel();
        jLabelCmdCtr = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();
        jButtonLand = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelDebugCtr = new javax.swing.JLabel();
        jButtonTakeoffLand = new javax.swing.JButton();
        jButtonTest1 = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jPanelAccel = new javax.swing.JPanel();
        jLabelAccelerometer = new javax.swing.JLabel();
        jLabelAccelX = new javax.swing.JLabel();
        jTextFieldAccelX = new javax.swing.JTextField();
        jLabelAccelY = new javax.swing.JLabel();
        jTextFieldAccelY = new javax.swing.JTextField();
        jLabelAccelZ = new javax.swing.JLabel();
        jTextFieldAccelZ = new javax.swing.JTextField();
        jPanelGyro = new javax.swing.JPanel();
        jLabelGyro = new javax.swing.JLabel();
        jLabelGyroX = new javax.swing.JLabel();
        jTextFieldGyroX = new javax.swing.JTextField();
        jLabelGyroY = new javax.swing.JLabel();
        jTextFieldGyroY = new javax.swing.JTextField();
        jLabelGyroZ = new javax.swing.JLabel();
        jTextFieldGyroZ = new javax.swing.JTextField();
        jPanelCompass = new javax.swing.JPanel();
        jLabelCompass = new javax.swing.JLabel();
        jLabelCompX = new javax.swing.JLabel();
        jTextFieldCompassX = new javax.swing.JTextField();
        jLabelCompY = new javax.swing.JLabel();
        jTextFieldCompassY = new javax.swing.JTextField();
        jLabelCompZ = new javax.swing.JLabel();
        jTextFieldCompassZ = new javax.swing.JTextField();
        jPanelBattery = new javax.swing.JPanel();
        jLabelBattery = new javax.swing.JLabel();
        jProgressBarBattery = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldComPort = new javax.swing.JTextField();
        jTextFieldArmState = new javax.swing.JTextField();
        jTextFieldMode = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldXbeeStatus = new javax.swing.JTextField();
        jPanelLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jPanelAbout = new javax.swing.JPanel();
        jLabelProjectReqs = new javax.swing.JLabel();
        jScrollPanel = new javax.swing.JScrollPane();
        jTextAreaProjReqs = new javax.swing.JTextArea();
        jLabelTeam6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSendTPID = new javax.swing.JButton();
        jTextFieldTPID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPPID = new javax.swing.JTextField();
        jButtonSendPPID = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonSendYPID = new javax.swing.JButton();
        jTextFieldYPID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonSendRPID = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldRPID = new javax.swing.JTextField();
        jLabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FireScout Control Center");
        setPreferredSize(new java.awt.Dimension(800, 650));

        jPanelBase.setBackground(java.awt.SystemColor.controlLtHighlight);

        jPanelQuadStatus.setBackground(java.awt.SystemColor.activeCaption);

        jPanelCmdCtrBase.setBackground(java.awt.SystemColor.inactiveCaption);

        jLabelCmdCtr.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        jLabelCmdCtr.setText("Command Center");

        jButtonStart.setBackground(new java.awt.Color(13, 158, 13));
        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonReturn.setText("Return to Base");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jButtonLand.setText("Land");
        jButtonLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCmdCtrBaseLayout = new javax.swing.GroupLayout(jPanelCmdCtrBase);
        jPanelCmdCtrBase.setLayout(jPanelCmdCtrBaseLayout);
        jPanelCmdCtrBaseLayout.setHorizontalGroup(
            jPanelCmdCtrBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCmdCtr, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addGroup(jPanelCmdCtrBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCmdCtrBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCmdCtrBaseLayout.setVerticalGroup(
            jPanelCmdCtrBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCmdCtrBaseLayout.createSequentialGroup()
                .addComponent(jLabelCmdCtr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLand)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(java.awt.SystemColor.inactiveCaption);

        jLabelDebugCtr.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        jLabelDebugCtr.setText("  Debug Center");

        jButtonTakeoffLand.setBackground(java.awt.SystemColor.controlShadow);
        jButtonTakeoffLand.setText("Takeoff & Land");
        jButtonTakeoffLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeoffLandActionPerformed(evt);
            }
        });

        jButtonTest1.setBackground(java.awt.SystemColor.controlShadow);
        jButtonTest1.setText("Test 1");
        jButtonTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTest1ActionPerformed(evt);
            }
        });

        jButtonStop.setBackground(new java.awt.Color(229, 38, 38));
        jButtonStop.setText("STOP");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelDebugCtr)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTakeoffLand, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jButtonTest1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelDebugCtr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTakeoffLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTest1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelAccelerometer.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabelAccelerometer.setText("Accelerometer");

        jLabelAccelX.setText("x:");

        jTextFieldAccelX.setEditable(false);
        jTextFieldAccelX.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldAccelX.setText("0.0");
        jTextFieldAccelX.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAccelX.setEnabled(false);
        jTextFieldAccelX.setFocusable(false);

        jLabelAccelY.setText("y:");

        jTextFieldAccelY.setEditable(false);
        jTextFieldAccelY.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldAccelY.setText("0.0");
        jTextFieldAccelY.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAccelY.setEnabled(false);
        jTextFieldAccelY.setFocusable(false);

        jLabelAccelZ.setText("z:");

        jTextFieldAccelZ.setEditable(false);
        jTextFieldAccelZ.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldAccelZ.setText("0.0");
        jTextFieldAccelZ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldAccelZ.setEnabled(false);
        jTextFieldAccelZ.setFocusable(false);

        javax.swing.GroupLayout jPanelAccelLayout = new javax.swing.GroupLayout(jPanelAccel);
        jPanelAccel.setLayout(jPanelAccelLayout);
        jPanelAccelLayout.setHorizontalGroup(
            jPanelAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccelLayout.createSequentialGroup()
                .addComponent(jLabelAccelerometer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelAccelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAccelX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAccelX, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAccelY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAccelY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAccelZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAccelZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAccelLayout.setVerticalGroup(
            jPanelAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccelLayout.createSequentialGroup()
                .addComponent(jLabelAccelerometer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAccelZ)
                        .addComponent(jTextFieldAccelZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAccelY)
                        .addComponent(jTextFieldAccelY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAccelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAccelX)
                        .addComponent(jTextFieldAccelX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabelGyro.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabelGyro.setText("Gryoscope");

        jLabelGyroX.setText("x:");

        jTextFieldGyroX.setEditable(false);
        jTextFieldGyroX.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldGyroX.setText("0.0");
        jTextFieldGyroX.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldGyroX.setEnabled(false);
        jTextFieldGyroX.setFocusable(false);

        jLabelGyroY.setText("y:");

        jTextFieldGyroY.setEditable(false);
        jTextFieldGyroY.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldGyroY.setText("0.0");
        jTextFieldGyroY.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldGyroY.setEnabled(false);
        jTextFieldGyroY.setFocusable(false);

        jLabelGyroZ.setText("z:");

        jTextFieldGyroZ.setEditable(false);
        jTextFieldGyroZ.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldGyroZ.setText("0.0");
        jTextFieldGyroZ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldGyroZ.setEnabled(false);
        jTextFieldGyroZ.setFocusable(false);

        javax.swing.GroupLayout jPanelGyroLayout = new javax.swing.GroupLayout(jPanelGyro);
        jPanelGyro.setLayout(jPanelGyroLayout);
        jPanelGyroLayout.setHorizontalGroup(
            jPanelGyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGyroLayout.createSequentialGroup()
                .addComponent(jLabelGyro)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelGyroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGyroX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGyroX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGyroY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGyroY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGyroZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldGyroZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGyroLayout.setVerticalGroup(
            jPanelGyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGyroLayout.createSequentialGroup()
                .addComponent(jLabelGyro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGyroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGyroX)
                    .addComponent(jTextFieldGyroX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGyroY)
                    .addComponent(jTextFieldGyroY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGyroZ)
                    .addComponent(jTextFieldGyroZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabelCompass.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabelCompass.setText("Compass");

        jLabelCompX.setText("x:");

        jTextFieldCompassX.setEditable(false);
        jTextFieldCompassX.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldCompassX.setText("0.0");
        jTextFieldCompassX.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCompassX.setEnabled(false);
        jTextFieldCompassX.setFocusable(false);

        jLabelCompY.setText("y:");

        jTextFieldCompassY.setEditable(false);
        jTextFieldCompassY.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldCompassY.setText("0.0");
        jTextFieldCompassY.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCompassY.setEnabled(false);
        jTextFieldCompassY.setFocusable(false);

        jLabelCompZ.setText("z:");

        jTextFieldCompassZ.setEditable(false);
        jTextFieldCompassZ.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jTextFieldCompassZ.setText("0.0");
        jTextFieldCompassZ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCompassZ.setEnabled(false);
        jTextFieldCompassZ.setFocusable(false);

        javax.swing.GroupLayout jPanelCompassLayout = new javax.swing.GroupLayout(jPanelCompass);
        jPanelCompass.setLayout(jPanelCompassLayout);
        jPanelCompassLayout.setHorizontalGroup(
            jPanelCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompassLayout.createSequentialGroup()
                .addComponent(jLabelCompass)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelCompassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCompX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCompassX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCompY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCompassY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCompZ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCompassZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelCompassLayout.setVerticalGroup(
            jPanelCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompassLayout.createSequentialGroup()
                .addComponent(jLabelCompass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCompassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompX)
                    .addComponent(jTextFieldCompassX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCompY)
                    .addComponent(jTextFieldCompassY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCompZ)
                    .addComponent(jTextFieldCompassZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabelBattery.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jLabelBattery.setText("Battery");

        jProgressBarBattery.setString("0");

        javax.swing.GroupLayout jPanelBatteryLayout = new javax.swing.GroupLayout(jPanelBattery);
        jPanelBattery.setLayout(jPanelBatteryLayout);
        jPanelBatteryLayout.setHorizontalGroup(
            jPanelBatteryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatteryLayout.createSequentialGroup()
                .addComponent(jLabelBattery)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelBatteryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBarBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBatteryLayout.setVerticalGroup(
            jPanelBatteryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBatteryLayout.createSequentialGroup()
                .addComponent(jLabelBattery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarBattery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(java.awt.SystemColor.controlHighlight);

        jTextFieldComPort.setEditable(false);
        jTextFieldComPort.setText("Connected to COM.");
        jTextFieldComPort.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jTextFieldComPort.setEnabled(false);

        jTextFieldArmState.setText("---");
        jTextFieldArmState.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldArmState.setEnabled(false);

        jTextFieldMode.setText("---");
        jTextFieldMode.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMode.setEnabled(false);

        jLabelStatus.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        jLabelStatus.setText("Status");

        jTextFieldXbeeStatus.setText("xBee not connected.");
        jTextFieldXbeeStatus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldXbeeStatus.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelStatus)
                    .addComponent(jTextFieldMode)
                    .addComponent(jTextFieldComPort, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jTextFieldArmState)
                    .addComponent(jTextFieldXbeeStatus))
                .addGap(3, 3, 3))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelStatus)
                .addGap(2, 2, 2)
                .addComponent(jTextFieldArmState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldXbeeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldComPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelQuadStatusLayout = new javax.swing.GroupLayout(jPanelQuadStatus);
        jPanelQuadStatus.setLayout(jPanelQuadStatusLayout);
        jPanelQuadStatusLayout.setHorizontalGroup(
            jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuadStatusLayout.createSequentialGroup()
                .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuadStatusLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelCmdCtrBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelQuadStatusLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanelAccel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelQuadStatusLayout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(jPanelGyro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuadStatusLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuadStatusLayout.createSequentialGroup()
                        .addGap(0, 97, Short.MAX_VALUE)
                        .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBattery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelCompass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
        );
        jPanelQuadStatusLayout.setVerticalGroup(
            jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQuadStatusLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAccel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCompass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGyro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBattery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQuadStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelCmdCtrBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Quadcopter Status", jPanelQuadStatus);

        jPanelLog.setBackground(java.awt.SystemColor.activeCaption);

        jTextAreaLog.setEditable(false);
        jTextAreaLog.setColumns(20);
        jTextAreaLog.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextAreaLog.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLog);

        javax.swing.GroupLayout jPanelLogLayout = new javax.swing.GroupLayout(jPanelLog);
        jPanelLog.setLayout(jPanelLogLayout);
        jPanelLogLayout.setHorizontalGroup(
            jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );
        jPanelLogLayout.setVerticalGroup(
            jPanelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        jTabbedPaneMain.addTab("On-Screen Log", jPanelLog);

        jPanelAbout.setBackground(java.awt.SystemColor.activeCaption);

        jLabelProjectReqs.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelProjectReqs.setText("Project Requirements");

        jTextAreaProjReqs.setEditable(false);
        jTextAreaProjReqs.setBackground(java.awt.SystemColor.inactiveCaption);
        jTextAreaProjReqs.setColumns(20);
        jTextAreaProjReqs.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextAreaProjReqs.setRows(5);
        jTextAreaProjReqs.setText("1. Copter must scan area of at least 1000 square feet.\n2. Minimum search time is 15 minutes.\n3. Must maintain addtional three minutes for return trip.\n4. Must identify existence and relative position of humans. \n5. Must return relative coordinates of detected humans.\n6. Must scan every room at least once. \n7. Must return to starting point at end of mission. ");
        jScrollPanel.setViewportView(jTextAreaProjReqs);

        jLabelTeam6.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabelTeam6.setText("Team 6");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(java.awt.SystemColor.inactiveCaption);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Mikhail Andreev\nGabriel Begun\nBenjamin Corman\nJonah Lou\nKelsey Warda");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProjectReqs)
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTeam6)
                    .addGroup(jPanelAboutLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProjectReqs)
                    .addComponent(jLabelTeam6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("About", jPanelAbout);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        jButtonSendTPID.setText("Send PID");
        jButtonSendTPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendTPIDActionPerformed(evt);
            }
        });

        jTextFieldTPID.setText("0.3,0.1,0.1");

        jLabel3.setText("Throttle");

        jTextFieldPPID.setText("0.3,0.1,0.1");

        jButtonSendPPID.setText("Send PID");
        jButtonSendPPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendPPIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Pitch");

        jButtonSendYPID.setText("Send PID");
        jButtonSendYPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendYPIDActionPerformed(evt);
            }
        });

        jTextFieldYPID.setText("0.3,0.1,0.1");

        jLabel5.setText("Yaw");

        jButtonSendRPID.setText("Send PID");
        jButtonSendRPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendRPIDActionPerformed(evt);
            }
        });

        jLabel6.setText("Roll");

        jTextFieldRPID.setText("0.3,0.1,0.1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendTPID)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendPPID)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldYPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendYPID)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendRPID)
                    .addComponent(jLabel6))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSendRPID))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldYPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSendYPID))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSendPPID))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSendTPID)))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("Send PID", jPanel2);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAFDLogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 40)); // NOI18N
        jLabel1.setText("FireScout Command Suite");

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addComponent(jTabbedPaneMain)
                        .addContainerGap())
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogo)
                        .addGap(31, 31, 31))))
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addComponent(jLabelLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBaseLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addComponent(jTabbedPaneMain)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void parseInformation(String str) {
        jTextFieldXbeeStatus.setText("Xbee Connected.");
        if (str.length() < 10) {
            return;
        } else {
            String dataArray[] = str.substring(9).split(",");

            switch (dataArray[0].substring(0, 1)) {
                case "a":
                    jTextFieldAccelX.setText(dataArray[0].substring(2));
                    jTextFieldAccelY.setText(dataArray[1].substring(2));
                    jTextFieldAccelZ.setText(dataArray[2].substring(2));
                    break;
                case "g":
                    jTextFieldGyroX.setText(dataArray[0].substring(2));
                    jTextFieldGyroY.setText(dataArray[1].substring(2));
                    jTextFieldGyroZ.setText(dataArray[2].substring(2));
                    break;
                case "c":
                    jTextFieldCompassX.setText(dataArray[0].substring(2));
                    jTextFieldCompassY.setText(dataArray[1].substring(2));
                    jTextFieldCompassZ.setText(dataArray[2].substring(2));
                    break;
                case "m":
                    if (dataArray[0].substring(2).equals("0")) {
                        jTextFieldMode.setText("AUTOMATIC MODE");
                    } else {
                        jTextFieldMode.setText("MANUAL MODE");
                    }

                    if (dataArray[1].substring(2).equals("0")) {
                        jTextFieldArmState.setText("DISARMED");
                    } else {
                        jTextFieldArmState.setText("ARMED");
                    }
                    break;

                //voltage, current, mah, 
            }
        }

    }

    private class GUISerialPortEventListener implements SerialPortEventListener {
        public synchronized void serialEvent(SerialPortEvent oEvent) {
            if (oEvent.getEventType() == SerialPortEvent.DATA_AVAILABLE) {
                try {
                    Date date = new Date();
                    String inputLine = mySerialComm.input.readLine();
                    jTextAreaLog.append(date.toString() + "\t\t" + inputLine + "\n");

                    if (inputLine.length() > 7 && inputLine.substring(0, 7).equals("PilotIn")) {
                        parseInformation(inputLine);
                    }

                    try {
                        FileWriter fstream = new FileWriter("log.txt", true);
                        BufferedWriter out = new BufferedWriter(fstream);
                        out.write(date.toString() + "\t" + inputLine + "\n");
                        //Close the output stream
                        out.close();
                    } catch (Exception e) {//Catch exception if any
                        System.err.println("Error: " + e.getMessage());
                    }
                } catch (Exception e) {
                    System.err.println(e.toString()); // TODO
                }
            } else { // Ignore all the other eventTypes, but you should consider
                // the other ones.
                System.out.println("Serial Port Event not handled received");
            }

        }
    }

    public void onScreenLog(String str) {
        Date date = new Date();
        jTextAreaLog.append(date.toString() + "\t" + str + "\n");

    }

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        parseInformation("PilotIn: mo0,ar0");
        try {
            mySerialComm.output.write("Start\n".getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        try {
            mySerialComm.output.write("Return\n".getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        try {
            mySerialComm.output.write("Stop\n".getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonTakeoffLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeoffLandActionPerformed
        try {
            mySerialComm.output.write("TakeoffLand\n".getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonTakeoffLandActionPerformed

    private void jButtonTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTest1ActionPerformed
        try {
            mySerialComm.output.write("Test1\n".getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonTest1ActionPerformed

    private void jButtonSendTPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendTPIDActionPerformed
        try {
            mySerialComm.output.write(("TPID " + jTextFieldTPID.getText() + "\n").getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonSendTPIDActionPerformed

    private void jButtonSendPPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendPPIDActionPerformed
        try {
            mySerialComm.output.write(("PPID " + jTextFieldPPID.getText() + "\n").getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonSendPPIDActionPerformed

    private void jButtonSendYPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendYPIDActionPerformed
        try {
            mySerialComm.output.write(("YPID " + jTextFieldYPID.getText() + "\n").getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonSendYPIDActionPerformed

    private void jButtonSendRPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendRPIDActionPerformed
        try {
            mySerialComm.output.write(("RPID " + jTextFieldRPID.getText() + "\n").getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonSendRPIDActionPerformed

    private void jButtonLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLandActionPerformed
        try {
            mySerialComm.output.write("Land\n".getBytes());
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButtonLandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FireScoutGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FireScoutGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FireScoutGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FireScoutGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FireScoutGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLand;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonSendPPID;
    private javax.swing.JButton jButtonSendRPID;
    private javax.swing.JButton jButtonSendTPID;
    private javax.swing.JButton jButtonSendYPID;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JButton jButtonTakeoffLand;
    private javax.swing.JButton jButtonTest1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAccelX;
    private javax.swing.JLabel jLabelAccelY;
    private javax.swing.JLabel jLabelAccelZ;
    private javax.swing.JLabel jLabelAccelerometer;
    private javax.swing.JLabel jLabelBattery;
    private javax.swing.JLabel jLabelCmdCtr;
    private javax.swing.JLabel jLabelCompX;
    private javax.swing.JLabel jLabelCompY;
    private javax.swing.JLabel jLabelCompZ;
    private javax.swing.JLabel jLabelCompass;
    private javax.swing.JLabel jLabelDebugCtr;
    private javax.swing.JLabel jLabelGyro;
    private javax.swing.JLabel jLabelGyroX;
    private javax.swing.JLabel jLabelGyroY;
    private javax.swing.JLabel jLabelGyroZ;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelProjectReqs;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTeam6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelAccel;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelBattery;
    private javax.swing.JPanel jPanelCmdCtrBase;
    private javax.swing.JPanel jPanelCompass;
    private javax.swing.JPanel jPanelGyro;
    private javax.swing.JPanel jPanelLog;
    private javax.swing.JPanel jPanelQuadStatus;
    private javax.swing.JProgressBar jProgressBarBattery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPanel;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextArea jTextAreaProjReqs;
    private javax.swing.JTextField jTextFieldAccelX;
    private javax.swing.JTextField jTextFieldAccelY;
    private javax.swing.JTextField jTextFieldAccelZ;
    private javax.swing.JTextField jTextFieldArmState;
    private javax.swing.JTextField jTextFieldComPort;
    private javax.swing.JTextField jTextFieldCompassX;
    private javax.swing.JTextField jTextFieldCompassY;
    private javax.swing.JTextField jTextFieldCompassZ;
    private javax.swing.JTextField jTextFieldGyroX;
    private javax.swing.JTextField jTextFieldGyroY;
    private javax.swing.JTextField jTextFieldGyroZ;
    private javax.swing.JTextField jTextFieldMode;
    private javax.swing.JTextField jTextFieldPPID;
    private javax.swing.JTextField jTextFieldRPID;
    private javax.swing.JTextField jTextFieldTPID;
    private javax.swing.JTextField jTextFieldXbeeStatus;
    private javax.swing.JTextField jTextFieldYPID;
    // End of variables declaration//GEN-END:variables
}
